import { ReactScanner } from "@/components/react-scanner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ModeToggle } from "@/components/mode-toggle";
import { Providers } from "@/components/providers";
import { SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/features/sidebar/components/main";
import { AppSidebarTrigger } from "@/features/sidebar/components/trigger";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Proto-3",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReactScanner />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar />
          <SidebarInset>
            <AppSidebarTrigger className="fixed top-2 left-2" />
            {children}
          </SidebarInset>
          <ModeToggle className="fixed top-2 right-2" />
        </Providers>
      </body>
    </html>
  );
}
