name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - ".gitattributes"
      - ".env.example"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - ".gitattributes"
      - ".env.example"

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - command: "check-types"
            name: "Type Check"
          - command: "lint"
            name: "Lint"
          - command: "format:check"
            name: "Format Check"

    name: ${{ matrix.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Run ${{ matrix.command }} command with pnpm
        run: pnpm run ${{ matrix.command }}
